name: "Terraform CI/CD"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  terraform:
    name: "Terraform Plan & Apply"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        working-directory: .
        run: pip install -r requirements.txt

      - name: Run Pytest
        working-directory: .
        run: pytest test_pipeline.py -v

      - name: Bundle Lambda dependencies
        working-directory: .
        run: pip install -r lambda/generator/requirements.txt -t lambda/generator/vendor --no-compile
        
      - name: Build scikit-learn layer
        working-directory: .
        run: |
          pip install -r layer_requirements.txt -t layer/python --platform manylinux_2_28_x86_64 --platform manylinux2014_x86_64 --only-binary=:all: --python-version 3.12 --implementation cp --no-compile
      

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.16.3

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -no-color -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve tfplan